#pragma once

#include <X11/keysym.h>
#include <X11/X.h>

enum VirtualKeys
{
    VK_LBUTTON = Button1,        // Left mouse button
    VK_MBUTTON = Button2,        // Middle mouse button
    VK_RBUTTON = Button3,        // Right mouse button
    VK_SCROLL_UP = Button4,      // Scroll up
    VK_SCROLL_DOWN = Button5,    // Scroll down
    VK_XBUTTON1 = 0x08,          // Mouse4 thumb button (back)
    VK_XBUTTON2 = 0x09,          // Mouse5 thumb button (forward)
    
    VK_CANCEL = XK_Cancel,

    VK_BACK = XK_BackSpace,
    VK_TAB = XK_Tab,
    
    VK_CLEAR = XK_Clear,
    VK_RETURN = XK_Return,
    
    VK_SHIFT = XK_Shift_L,
    VK_CONTROL = XK_Control_L,
    VK_MENU = XK_Alt_L,
    VK_PAUSE = XK_Pause,
    VK_CAPITAL = XK_Caps_Lock,
    
    VK_ESCAPE = XK_Escape,
    
    VK_SPACE = XK_KP_Space,
    VK_PRIOR = XK_Prior,
    VK_NEXT = XK_Next,
    VK_END = XK_End,
    VK_HOME = XK_Home,
    VK_LEFT = XK_Left,
    VK_UP = XK_Up,
    VK_RIGHT = XK_Right,
    VK_DOWN = XK_Down,
    VK_SELECT = XK_Select,
    VK_EXECUTE = XK_Execute,
    VK_SNAPSHOT = XK_Print,
    VK_INSERT = XK_Insert,
    VK_DELETE = XK_Delete,
    VK_HELP = XK_Help,

    VK_0 = XK_0,
    VK_1 = XK_1,
    VK_2 = XK_2,
    VK_3 = XK_3,
    VK_4 = XK_4,
    VK_5 = XK_5,
    VK_6 = XK_6,
    VK_7 = XK_7,
    VK_8 = XK_8,
    VK_9 = XK_9,

    VK_A = XK_A,
    VK_B = XK_B,
    VK_C = XK_C,
    VK_D = XK_D,
    VK_E = XK_E,
    VK_F = XK_F,
    VK_G = XK_G,
    VK_H = XK_H,
    VK_I = XK_I,
    VK_J = XK_J,
    VK_K = XK_K,
    VK_L = XK_L,
    VK_M = XK_M,
    VK_N = XK_N,
    VK_O = XK_O,
    VK_P = XK_P,
    VK_Q = XK_Q,
    VK_R = XK_R,
    VK_S = XK_S,
    VK_T = XK_T,
    VK_U = XK_U,
    VK_V = XK_V,
    VK_W = XK_W,
    VK_X = XK_X,
    VK_Y = XK_Y,
    VK_Z = XK_Z,

    VK_a = XK_a,
    VK_b = XK_b,
    VK_c = XK_c,
    VK_d = XK_d,
    VK_e = XK_e,
    VK_f = XK_f,
    VK_g = XK_g,
    VK_h = XK_h,
    VK_i = XK_i,
    VK_j = XK_j,
    VK_k = XK_k,
    VK_l = XK_l,
    VK_m = XK_m,
    VK_n = XK_n,
    VK_o = XK_o,
    VK_p = XK_p,
    VK_q = XK_q,
    VK_r = XK_r,
    VK_s = XK_s,
    VK_t = XK_t,
    VK_u = XK_u,
    VK_v = XK_v,
    VK_w = XK_w,
    VK_x = XK_x,
    VK_y = XK_y,
    VK_z = XK_z,

    VK_EXCLAM = XK_exclam,
    VK_QUOTEDBL = XK_quotedbl,
    VK_NUMBERSIGN = XK_numbersign,
    VK_DOLLAR = XK_dollar,
    VK_PERCENT = XK_percent,
    VK_AMPERSAND = XK_ampersand,
    VK_APOSTROPHE = XK_apostrophe,
    VK_PARENLEFT = XK_parenleft,
    VK_PARENRIGHT = XK_parenright,
    VK_ASTERISK = XK_asterisk,
    VK_PLUS = XK_plus,
    VK_COMMA = XK_comma,
    VK_MINUS = XK_minus,
    VK_PERIOD = XK_period,
    VK_SLASH = XK_slash,
    VK_COLON = XK_colon,
    VK_SEMICOLON = XK_semicolon,
    VK_LESS = XK_less,
    VK_EQUAL = XK_equal,
    VK_GREATER = XK_greater,
    VK_QUESTION = XK_question,
    VK_AT = XK_at,
    VK_GRAVE = XK_grave,
    VK_UNDERSCORE = XK_underscore,
    VK_ASCIICIRCUM = XK_asciicircum,
    VK_BRACKETLEFT = XK_bracketleft,
    VK_BACKSLASH = XK_backslash,
    VK_BRACKETRIGHT = XK_bracketright,
    VK_ASCIITILDE = XK_asciitilde,
    VK_BRACELEFT = XK_braceleft,
    VK_BAR = XK_bar,
    VK_BRACERIGHT = XK_braceright,
    
    VK_LWIN = XK_Super_L,
    VK_RWIN = XK_Super_R,
    VK_APPS = XK_Menu,
    
    VK_NUMPAD0 = XK_KP_0,
    VK_NUMPAD1 = XK_KP_1,
    VK_NUMPAD2 = XK_KP_2,
    VK_NUMPAD3 = XK_KP_3,
    VK_NUMPAD4 = XK_KP_4,
    VK_NUMPAD5 = XK_KP_5,
    VK_NUMPAD6 = XK_KP_6,
    VK_NUMPAD7 = XK_KP_7,
    VK_NUMPAD8 = XK_KP_8,
    VK_NUMPAD9 = XK_KP_9,
    VK_MULTIPLY = XK_KP_Multiply,
    VK_ADD = XK_KP_Add,
    VK_SEPARATOR = XK_KP_Separator,
    VK_SUBTRACT = XK_KP_Subtract,
    VK_DECIMAL = XK_KP_Decimal,
    VK_DIVIDE = XK_KP_Divide,
    
    VK_F1 = XK_F1,
    VK_F2 = XK_F2,
    VK_F3 = XK_F3,
    VK_F4 = XK_F4,
    VK_F5 = XK_F5,
    VK_F6 = XK_F6,
    VK_F7 = XK_F7,
    VK_F8 = XK_F8,
    VK_F9 = XK_F9,
    VK_F10 = XK_F10,
    VK_F11 = XK_F11,
    VK_F12 = XK_F12,
    VK_F13 = XK_F13,
    VK_F14 = XK_F14,
    VK_F15 = XK_F15,
    VK_F16 = XK_F16,
    VK_F17 = XK_F17,
    VK_F18 = XK_F18,
    VK_F19 = XK_F19,
    VK_F20 = XK_F20,
    VK_F21 = XK_F21,
    VK_F22 = XK_F22,
    VK_F23 = XK_F23,
    VK_F24 = XK_F24,

    VK_NUMLOCK = XK_Num_Lock,
    VK_SCROLL = XK_Scroll_Lock,

    VK_LSHIFT = XK_Shift_L,
    VK_RSHIFT = XK_Shift_R,
    VK_LCONTROL = XK_Control_L,
    VK_RCONTROL = XK_Control_R,
    VK_LMENU = XK_Alt_L,
    VK_RMENU = XK_Alt_R
};