#pragma once

#include <xkbcommon/xkbcommon-keysyms.h>

enum VirtualKeys
{
    VK_LBUTTON      = XKB_KEY_Pointer_Button1,
    VK_MBUTTON      = XKB_KEY_Pointer_Button2,
    VK_RBUTTON      = XKB_KEY_Pointer_Button3,
    VK_SCROLL_UP    = XKB_KEY_XF86ScrollUp,
    VK_SCROLL_DOWN  = XKB_KEY_XF86ScrollDown,
    VK_XBUTTON1     = XKB_KEY_Pointer_Button4,
    VK_XBUTTON2     = XKB_KEY_Pointer_Button5,
    
    VK_CANCEL = XKB_KEY_Cancel,

    VK_BACK = XKB_KEY_BackSpace,
    VK_TAB = XKB_KEY_Tab,
    
    VK_CLEAR = XKB_KEY_Clear,
    VK_RETURN = XKB_KEY_Return,
    
    VK_SHIFT = XKB_KEY_Shift_L,
    VK_CONTROL = XKB_KEY_Control_L,
    VK_MENU = XKB_KEY_Alt_L,
    VK_PAUSE = XKB_KEY_Pause,
    VK_CAPITAL = XKB_KEY_Caps_Lock,
    
    VK_ESCAPE = XKB_KEY_Escape,
    
    VK_SPACE = XKB_KEY_KP_Space,
    VK_PRIOR = XKB_KEY_Prior,
    VK_NEXT = XKB_KEY_Next,
    VK_END = XKB_KEY_End,
    VK_HOME = XKB_KEY_Home,
    VK_LEFT = XKB_KEY_Left,
    VK_UP = XKB_KEY_Up,
    VK_RIGHT = XKB_KEY_Right,
    VK_DOWN = XKB_KEY_Down,
    VK_SELECT = XKB_KEY_Select,
    VK_EXECUTE = XKB_KEY_Execute,
    VK_SNAPSHOT = XKB_KEY_Print,
    VK_INSERT = XKB_KEY_Insert,
    VK_DELETE = XKB_KEY_Delete,
    VK_HELP = XKB_KEY_Help,

    VK_0 = XKB_KEY_0,
    VK_1 = XKB_KEY_1,
    VK_2 = XKB_KEY_2,
    VK_3 = XKB_KEY_3,
    VK_4 = XKB_KEY_4,
    VK_5 = XKB_KEY_5,
    VK_6 = XKB_KEY_6,
    VK_7 = XKB_KEY_7,
    VK_8 = XKB_KEY_8,
    VK_9 = XKB_KEY_9,

    VK_A = XKB_KEY_A,
    VK_B = XKB_KEY_B,
    VK_C = XKB_KEY_C,
    VK_D = XKB_KEY_D,
    VK_E = XKB_KEY_E,
    VK_F = XKB_KEY_F,
    VK_G = XKB_KEY_G,
    VK_H = XKB_KEY_H,
    VK_I = XKB_KEY_I,
    VK_J = XKB_KEY_J,
    VK_K = XKB_KEY_K,
    VK_L = XKB_KEY_L,
    VK_M = XKB_KEY_M,
    VK_N = XKB_KEY_N,
    VK_O = XKB_KEY_O,
    VK_P = XKB_KEY_P,
    VK_Q = XKB_KEY_Q,
    VK_R = XKB_KEY_R,
    VK_S = XKB_KEY_S,
    VK_T = XKB_KEY_T,
    VK_U = XKB_KEY_U,
    VK_V = XKB_KEY_V,
    VK_W = XKB_KEY_W,
    VK_X = XKB_KEY_X,
    VK_Y = XKB_KEY_Y,
    VK_Z = XKB_KEY_Z,

    VK_a = XKB_KEY_a,
    VK_b = XKB_KEY_b,
    VK_c = XKB_KEY_c,
    VK_d = XKB_KEY_d,
    VK_e = XKB_KEY_e,
    VK_f = XKB_KEY_f,
    VK_g = XKB_KEY_g,
    VK_h = XKB_KEY_h,
    VK_i = XKB_KEY_i,
    VK_j = XKB_KEY_j,
    VK_k = XKB_KEY_k,
    VK_l = XKB_KEY_l,
    VK_m = XKB_KEY_m,
    VK_n = XKB_KEY_n,
    VK_o = XKB_KEY_o,
    VK_p = XKB_KEY_p,
    VK_q = XKB_KEY_q,
    VK_r = XKB_KEY_r,
    VK_s = XKB_KEY_s,
    VK_t = XKB_KEY_t,
    VK_u = XKB_KEY_u,
    VK_v = XKB_KEY_v,
    VK_w = XKB_KEY_w,
    VK_x = XKB_KEY_x,
    VK_y = XKB_KEY_y,
    VK_z = XKB_KEY_z,

    VK_EXCLAM = XKB_KEY_exclam,
    VK_QUOTEDBL = XKB_KEY_quotedbl,
    VK_NUMBERSIGN = XKB_KEY_numbersign,
    VK_DOLLAR = XKB_KEY_dollar,
    VK_PERCENT = XKB_KEY_percent,
    VK_AMPERSAND = XKB_KEY_ampersand,
    VK_APOSTROPHE = XKB_KEY_apostrophe,
    VK_PARENLEFT = XKB_KEY_parenleft,
    VK_PARENRIGHT = XKB_KEY_parenright,
    VK_ASTERISK = XKB_KEY_asterisk,
    VK_PLUS = XKB_KEY_plus,
    VK_COMMA = XKB_KEY_comma,
    VK_MINUS = XKB_KEY_minus,
    VK_PERIOD = XKB_KEY_period,
    VK_SLASH = XKB_KEY_slash,
    VK_COLON = XKB_KEY_colon,
    VK_SEMICOLON = XKB_KEY_semicolon,
    VK_LESS = XKB_KEY_less,
    VK_EQUAL = XKB_KEY_equal,
    VK_GREATER = XKB_KEY_greater,
    VK_QUESTION = XKB_KEY_question,
    VK_AT = XKB_KEY_at,
    VK_GRAVE = XKB_KEY_grave,
    VK_UNDERSCORE = XKB_KEY_underscore,
    VK_ASCIICIRCUM = XKB_KEY_asciicircum,
    VK_BRACKETLEFT = XKB_KEY_bracketleft,
    VK_BACKSLASH = XKB_KEY_backslash,
    VK_BRACKETRIGHT = XKB_KEY_bracketright,
    VK_ASCIITILDE = XKB_KEY_asciitilde,
    VK_BRACELEFT = XKB_KEY_braceleft,
    VK_BAR = XKB_KEY_bar,
    VK_BRACERIGHT = XKB_KEY_braceright,
    
    VK_LWIN = XKB_KEY_Super_L,
    VK_RWIN = XKB_KEY_Super_R,
    VK_APPS = XKB_KEY_Menu,
    
    VK_NUMPAD0 = XKB_KEY_KP_0,
    VK_NUMPAD1 = XKB_KEY_KP_1,
    VK_NUMPAD2 = XKB_KEY_KP_2,
    VK_NUMPAD3 = XKB_KEY_KP_3,
    VK_NUMPAD4 = XKB_KEY_KP_4,
    VK_NUMPAD5 = XKB_KEY_KP_5,
    VK_NUMPAD6 = XKB_KEY_KP_6,
    VK_NUMPAD7 = XKB_KEY_KP_7,
    VK_NUMPAD8 = XKB_KEY_KP_8,
    VK_NUMPAD9 = XKB_KEY_KP_9,
    VK_MULTIPLY = XKB_KEY_KP_Multiply,
    VK_ADD = XKB_KEY_KP_Add,
    VK_SEPARATOR = XKB_KEY_KP_Separator,
    VK_SUBTRACT = XKB_KEY_KP_Subtract,
    VK_DECIMAL = XKB_KEY_KP_Decimal,
    VK_DIVIDE = XKB_KEY_KP_Divide,
    
    VK_F1 = XKB_KEY_F1,
    VK_F2 = XKB_KEY_F2,
    VK_F3 = XKB_KEY_F3,
    VK_F4 = XKB_KEY_F4,
    VK_F5 = XKB_KEY_F5,
    VK_F6 = XKB_KEY_F6,
    VK_F7 = XKB_KEY_F7,
    VK_F8 = XKB_KEY_F8,
    VK_F9 = XKB_KEY_F9,
    VK_F10 = XKB_KEY_F10,
    VK_F11 = XKB_KEY_F11,
    VK_F12 = XKB_KEY_F12,
    VK_F13 = XKB_KEY_F13,
    VK_F14 = XKB_KEY_F14,
    VK_F15 = XKB_KEY_F15,
    VK_F16 = XKB_KEY_F16,
    VK_F17 = XKB_KEY_F17,
    VK_F18 = XKB_KEY_F18,
    VK_F19 = XKB_KEY_F19,
    VK_F20 = XKB_KEY_F20,
    VK_F21 = XKB_KEY_F21,
    VK_F22 = XKB_KEY_F22,
    VK_F23 = XKB_KEY_F23,
    VK_F24 = XKB_KEY_F24,

    VK_NUMLOCK = XKB_KEY_Num_Lock,
    VK_SCROLL = XKB_KEY_Scroll_Lock,

    VK_LSHIFT = XKB_KEY_Shift_L,
    VK_RSHIFT = XKB_KEY_Shift_R,
    VK_LCONTROL = XKB_KEY_Control_L,
    VK_RCONTROL = XKB_KEY_Control_R,
    VK_LMENU = XKB_KEY_Alt_L,
    VK_RMENU = XKB_KEY_Alt_R
};